[keys]
circleci_org_slug = YOUR_CIRCLECI_ORG_SLUG # Akin to github/your_user_name
circleci_token = YOUR_CIRCLECI_TOKEN # Generate in CircleCI account settings

docker_username = YOUR_DOCKER_USERNAME
docker_password = YOUR_DOCKER_PWD
tf_cloud_key = YOUR_TERRAFORM_CLOUD_KEY
snyk_token = YOUR_SNYK_TOKEN


