[keys]
circleci_org_slug = "github/zmarkan" # Akin to github/your_user_name
circleci_org_id = "8995ddc0-b07a-4bc2-8eb6-816c67a512fa"
circleci_token = "91a0eb70e587236c21722623e608120df11ba4fb" # Generate in CircleCI account settings

circleci_context_id = "26273b1a-c23e-41cd-af7d-86055b11fa52"

docker_username = "zmarkan"
docker_password = "YOUR_DOCKER_PWD" 
docker_token = "dckr_pat_aImFHwr8gMBVfnvY-N9oGtvSe0Y"
tf_cloud_key = "YOUR_TERRAFORM_CLOUD_KEY"
snyk_token = "bd8e010b-38c9-4fd0-a32c-8ff0872cdad2"
digitalocean_token = "dop_v1_9294af212c3b36924e0fd46dbb9ffa9d3be8c0510236ba62f85ad94f683da822"

